name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    name: Testing and building
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
        
      - name: Install dependencies to root
        run: npm install

      - name: Install dependencies to backend
        run: cd backend && npm install  
        # working-directory: backend  # Run npm install in the backend directory

      - name: Install dependencies to frontend
        run: cd frontend && npm install  
        # working-directory: frontend
        
      - name: Check style
        run: npm run eslint
        working-directory: backend  # Run npm run eslint in the backend directory

      - name: Build frontend and copy to backend directory
        run: cd backend && npm run build:render

      - name: Start test server
        run: |
          npm run start:test &
          echo "Test server started"
        working-directory: backend

      - name: Wait for 10 seconds
        run: sleep 10

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: echo "Test server already started"
          wait-on: http://localhost:3001
        env:
          MONGODB_URI: ${{ secrets.MONGODB_TEST_URI }}
          SECRET: ${{ secrets.SECRET }}
        